name: todo-project
on:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v3
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Login on Harbor
        uses: docker/login-action@v2
        with: 
          registry: ${{ secrets.HARBOR_URL }}
          username: ${{ secrets.HARBOR_LOGIN }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{ secrets.HARBOR_URL }}/devops_trainee/todo:latest
          push: true
      - name: Update image on rancher
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBECONFIG }}
          command: -n todo patch deployment todo-all -p "{\"spec\":{\"template\":{\"metadata\":{ \"labels\":{  \"redeploy\":\"$(date +%s)\"}}}}}"
