name: todo-project
on:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v3
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d%m%Y-%H%M')"
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Login on Harbor
        uses: docker/login-action@v2
        with: 
          registry: ${{ secrets.HARBOR_URL }}
          username: ${{ secrets.HARBOR_LOGIN }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{ secrets.HARBOR_URL }}/devops_trainee/todo:${{ steps.date.outputs.date }}
          push: true
      - name: Update image on rancher
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBECONFIG }}
          command: -n todo set image deployment/todo-all todo-all=${{ secrets.HARBOR_URL }}/devops_trainee/todo:${{ steps.date.outputs.date }}
